baseURL = 'https://kwjo.github.io/'
languageCode = 'en-us'
title = 'kwjo.github.io'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = "Hi, I'm Kwan 👋"
homeIntroContent = """
I work as a clinical pharmacist at the NHS, passionate about advancing clinical pharmacy and integrating data science into healthcare. Feel free to reach out if you have any questions! **The content provided on this blog is for informational purposes only and is not intended as medical advice.**
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/kwjo/"

[[params.social]]
name = "github"
url = "https://github.com/kwjo"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "repository-clinical"
url = "/repository-clinical"

[[params.menu]]
name = "repository-data"
url = "/repository-data"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"